---
title: "Final Project Proposal"
output: github_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Names and UNIs
* Zhiye Lou (zl2978)  
* Chen Mo (cm4047)  

##  Project Title   
**Exploring the college enrollment rate in the United States**  

## Motivation  
One of the major social issues in the United States is the inequality in the college enrollment. It is important to find the relevant factors that influence the college enrollment rate among different people in the United States. We hope to explore the trend of the college enrollment rate from demographic and geographic aspects, as well as the relationship between those and school type (private school or not). Many studies have shown that the geography is one of the major reasons for the education inequalities, and we want to investigate if there are significant differences in college enrollment rate between different states after adjusting other demographic factors such as income and race.  

## The intended final products
* Any association between different income groups and the college enrollment rate?  
* Any association between geography (states and if from an urban) and the college enrollment rate?
* Any association between races and the college enrollment rate?  
* An national map which shows the details about the college enrollment rate  

## Data sources  
Our data is from https://usa.ipums.org/usa-action/ 

## Challenges & Planned Analyses  
* The dataset is extremely big (about 200000 rows).  
* The project may require many different maps, and the trend in these maps need to be shown clear.
* Create an interactivity map shown the states and college enrollment rate.
* Create a plot shown the relationship between family income and college enrollment rate.
* Create a plot shown the relationship between different races and college enrollment rate.  

## Timeline
* Week of 11/8: Data wrangling, exploration, and zoom review meeting. (Discuss what kind of results and graph we want to have)  
* Week of 11/15: Create the website and each person work on one tab of the website.  
* Week of 11/23: Write the report and each person work on one section.
* Week of 11/30: Final report and screencast.



