---
title: "Interactive map"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(leaflet)
library(plotly)
library(flexdashboard)
library(shiny)
```

```{r}
clean_df = read_csv("./cleaned.csv") %>% 
  mutate(
    college_attendance_status = recode(college_attendance_status, "Yes" = "1", "No" = "0"),
    college_attendance_status = as.numeric(college_attendance_status)
    ) %>% 
  mutate(
    metropolitan_status = recode(metropolitan_status, "in metropolitian but mixed of central city" = "In metropolitan", "in metropolitan and central city" = "In metropolitan", "in metroplitian but not in central city" = "In metropolitan")
  )
```

College Attendance Rate Over Time
===================================== 

Column {.sidebar}
-----------------------------------------------------------------------
```{r for_sidebar}
states_choices = clean_df %>% pull(states) %>% unique()
metropolitan_choices = clean_df %>% pull(metropolitan_status) %>% unique()
children_range = clean_df %>% pull(number_of_children)
income_range = clean_df %>% pull(number_of_children)

selectInput(
  "states_choice",
  label = h3("Select State"),
  choices = states_choices,
  selected = "NY"
)

sliderInput(
  "income_range",
  h3("Annually Family Income"),
  -20000, 150000, 
  value = c(-20000, 150000))

radioButtons(
  "metropolitan_choice",
  h3("Metropolitan Status"),
  choices = metropolitan_choices
)
```

Column {.tabset}
-----------------------------------------------------------------------

### College Attendance Rate Cross Time

```{r}
renderPlotly({
clean_df %>% 
  filter(
      states == input[["states_choice"]],
      metropolitan_status == input[["metropolitan_choice"]],
      anually_family_income %in% input[["income_range"]][1]:input[["income_range"]][2]) %>%
  group_by(year) %>%
  mutate(
    number_1 = "1",
    number_1 = as.numeric(number_1),
    college_attendance_rate = sum(college_attendance_status)/sum(number_1)
  ) %>% 
    ungroup() %>% 
  plot_ly(
    y = ~college_attendance_rate, x = ~year, color = ~states, mode = "lines+markers",
    type = "scatter", colors = "viridis")
})
```

